version: '3'
services:
  node:
    build:
      context: .
      dockerfile: node.dockerfile
    depends_on:
      - db
      - mongo
    ports:
      - "8080:8080"
    volumes:
      - ./:/var/www
      - /var/www/node_modules
    environment:
      PORT: 8080
      DATABASE_URL: postgres://postgres:changeme@db:5432/contests
      POSTGRES_PASSWORD: changeme
      POSTGRES_USER: postgres

  db:
    build:
      context: .
      dockerfile: postgres.dockerfile
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_USER=postgres
      - POSTGRES_DB=contests
    volumes:
      -  postgres:/var/lib/postgresql/data


  mongo:
    build:
      context: .
      dockerfile: mongo.dockerfile
    ports:
      - "8081:8081"
    environment:
      - MONGO_URL=mongodb://mongo:27017/contests
    volumes:
      - mongo:/var/lib/mongo/data

volumes:
  postgres:
    driver: local
  mongo:
    driver: local
