version: '3'
services:
  node:
    build:
      context: .
      dockerfile: node.dockerfile
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - nodeapp-network
    volumes:
      - ./:/var/www
    environment:
      DATABASE_URL: postgres://postgres:hello@postgres:5432/contests
#    - PGUSER=unicorn_user
#    - PGHOST=localhost
#    - PGPASSWORD=hello
#    - PGDATABASE=contests
#    - PGPORT=5432


#  mongo:
#    image: mongo
#    networks:
#      - nodeapp-network
#    volumes: [
#      '~/docker-volumes/host:/host',
#      '~/docker-volumes/mongo:/data/db'
#    ]

  postgres:
    image: postgres
#    restart: always
    networks:
      - nodeapp-network
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD="hello"
    volumes:
      -  postgres:/var/lib/postgresql/data

networks:
  nodeapp-network:
    driver: bridge

volumes:
  postgres:
    driver: local
